FROM node:20-alpine

WORKDIR /backend

COPY package.json .

RUN npm i \
    && npm cache clean --force \
    && rm -rf /root/.npm

COPY . .

#RUN npm run generate && npm run migrate

EXPOSE 4000

CMD ["npm", "run", "dev"]