import Providers from "@/providers/Providers";
import "../globals.css";
import SideBar from "@/components/Profile/SideBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="fa" dir="rtl" className="sticky top-0 overflow-y-hidden">
      <Providers>
        <body className={`antialiased bg-primary overflow-y-hidden`}>
          <main className="grid grid-cols-12 overflow-y-hidden">
            <section className="col-span-3 h-screen sticky top-0">
              <SideBar />
            </section>
            <section className="col-span-9 h-screen sticky top-0">
              <header className="w-full h-10 bg-primary"></header>
              <main className="sticky top-10 left-0 w-full h-screen rounded-tr-2xl bg-bg-primary p-5 px-6 overflow-y-auto pb-28">
                {children}
              </main>
            </section>
          </main>
        </body>
      </Providers>
    </html>
  );
}
